service: deplatformer-webapp

plugins:
  - serverless-python-requirements
  - serverless-wsgi

provider:
  name: aws
  runtime: python3.7

custom:
  wsgi:
    app: deplatformer_webapp.app.app
    packRequirements: false
  pythonRequirements:
    dockerizedPip: non-linux
    usePoetry: true

functions:
  app:
    handler: wsgi_handler.handler
