"""empty message

Revision ID: 127f5a5a0dab
Revises: 56f1339d6e2a
Create Date: 2020-12-30 12:44:27.511774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127f5a5a0dab'
down_revision = '56f1339d6e2a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_media():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade_media():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###

