"""empty message

Revision ID: 3e88b560dad5
Revises: 8361223c60ab
Create Date: 2020-12-23 00:53:41.833168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e88b560dad5'
down_revision = '8361223c60ab'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_facebook():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column("cover_photo_id")
        batch_op.add_column(sa.Column('cover_photo_id', sa.Integer, nullable=True))

    # ### end Alembic commands ###


def downgrade_facebook():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'media', ['cover_photo_id'], ['id'])

    # ### end Alembic commands ###

