"""empty message

Revision ID: 56f1339d6e2a
Revises: 
Create Date: 2020-12-29 19:00:03.673724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f1339d6e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_key',
                    sa.Column('encrypted_key', sa.String(), nullable=False),
                    sa.Column('iv', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('encrypted_key')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
                    sa.Column('username', sa.String(length=100, collation='NOCASE'), nullable=False),
                    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
                    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
                    sa.Column('first_name', sa.String(length=100, collation='NOCASE'), server_default='',
                              nullable=False),
                    sa.Column('last_name', sa.String(length=100, collation='NOCASE'), server_default='',
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('ffs_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ffs_userid', sa.String(length=36), nullable=True),
                    sa.Column('token', sa.String(length=36), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ffs_user_ffs_userid'), 'ffs_user', ['ffs_userid'], unique=False)
    op.create_index(op.f('ix_ffs_user_token'), 'ffs_user', ['token'], unique=False)
    op.create_table('logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('event', sa.String(length=255), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_directories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('platform', sa.String(), nullable=False),
                    sa.Column('directory', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('wallets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('ffs', sa.String(length=255), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('files',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('file_path', sa.String(length=255), nullable=True),
                    sa.Column('file_name', sa.String(length=255), nullable=True),
                    sa.Column('upload_date', sa.DateTime(), nullable=True),
                    sa.Column('file_size', sa.Integer(), nullable=True),
                    sa.Column('CID', sa.String(length=64), nullable=True),
                    sa.Column('platform', sa.String(length=255), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('ffs_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['ffs_id'], ['ffs_user.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_files_CID'), 'files', ['CID'], unique=False)
    op.create_index(op.f('ix_files_file_name'), 'files', ['file_name'], unique=False)
    op.create_index(op.f('ix_files_platform'), 'files', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_platform'), table_name='files')
    op.drop_index(op.f('ix_files_file_name'), table_name='files')
    op.drop_index(op.f('ix_files_CID'), table_name='files')
    op.drop_table('files')
    op.drop_table('wallets')
    op.drop_table('user_directories')
    op.drop_table('logs')
    op.drop_index(op.f('ix_ffs_user_token'), table_name='ffs_user')
    op.drop_index(op.f('ix_ffs_user_ffs_userid'), table_name='ffs_user')
    op.drop_table('ffs_user')
    op.drop_table('users')
    op.drop_table('user_key')
    # ### end Alembic commands ###


def upgrade_media():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_keys',
    sa.Column('enc_key', sa.String(), nullable=False),
    sa.Column('iv', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('enc_key', name=op.f('pk_file_keys'))
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('container_type', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('encrypted_file', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_filepath'), ['filepath'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_media_parent_id_container_type', ['parent_id', 'container_type'], unique=False)
        batch_op.create_index('ix_media_parent_id_media_type', ['parent_id', 'media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_post_id'), ['post_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('media_files', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('url_label', sa.String(), nullable=True),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('profile_update', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('tag_links',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_tag_links_post_id_posts')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_links_tag_id_tags')),
    sa.PrimaryKeyConstraint('tag_id', 'post_id', name=op.f('pk_tag_links'))
    )
    # ### end Alembic commands ###


def downgrade_media():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_links')
    op.drop_table('tags')
    op.drop_table('posts')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_post_id'))
        batch_op.drop_index('ix_media_parent_id_media_type')
        batch_op.drop_index('ix_media_parent_id_container_type')
        batch_op.drop_index(batch_op.f('ix_media_parent_id'))
        batch_op.drop_index(batch_op.f('ix_media_filepath'))

    op.drop_table('media')
    op.drop_table('file_keys')
    # ### end Alembic commands ###

