"""empty message

Revision ID: 56f1339d6e2a
Revises: 
Create Date: 2020-12-29 19:00:03.673724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f1339d6e2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_media():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_keys',
    sa.Column('enc_key', sa.String(), nullable=False),
    sa.Column('iv', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('enc_key', name=op.f('pk_file_keys'))
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('container_type', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('encrypted_file', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_filepath'), ['filepath'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_media_parent_id_container_type', ['parent_id', 'container_type'], unique=False)
        batch_op.create_index('ix_media_parent_id_media_type', ['parent_id', 'media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_post_id'), ['post_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('media_files', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('url_label', sa.String(), nullable=True),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('profile_update', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('tag_links',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_tag_links_post_id_posts')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_links_tag_id_tags')),
    sa.PrimaryKeyConstraint('tag_id', 'post_id', name=op.f('pk_tag_links'))
    )
    # ### end Alembic commands ###


def downgrade_media():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_links')
    op.drop_table('tags')
    op.drop_table('posts')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_post_id'))
        batch_op.drop_index('ix_media_parent_id_media_type')
        batch_op.drop_index('ix_media_parent_id_container_type')
        batch_op.drop_index(batch_op.f('ix_media_parent_id'))
        batch_op.drop_index(batch_op.f('ix_media_filepath'))

    op.drop_table('media')
    op.drop_table('file_keys')
    # ### end Alembic commands ###

