"""empty message

Revision ID: 8361223c60ab
Revises: ee7c53956893
Create Date: 2020-12-07 01:43:59.059623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8361223c60ab'
down_revision = 'ee7c53956893'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_facebook():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('media', sa.Column('thumbnail', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_facebook():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'thumbnail')
    op.drop_column('media', 'media_type')
    # ### end Alembic commands ###

